name: alz-early
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.24,<2.1
  - scipy>=1.10
  - pandas>=2.0
  - SimpleITK>=2.3
  - nibabel>=5.2
  - matplotlib>=3.7
  - tqdm>=4.66
  - pip
  - pip:
      - dcor>=0.6
